services:
  app:
    build:
      context: .
      dockerfile: ci-cd/dockerfiles/crypto.dockerfile
    ports: 
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    depends_on:
      - db
    networks:
      - app-network
  
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
    